CRUD/urls.py
from django.urls import path
from . import views
#
app_name='CRUD'
urlpatterns=[
    path('',views.DisplayList.as_view(),name='disp'),
    # path('enter/',views.enterDetails,name='enter'),
    path('enter/',views.EnterDetails.as_view(),name='enter'),
    path('<int:pk>/details/',views.DetailView.as_view(),name='details'),
    # path('edit/<int:id>/',views.editDetails,name='edit'),
    path('edit/<int:pk>/',views.EditDetails.as_view(),name='edit'),
    # path('delete/<int:id>/',views.deleteDetails,name='delete'),
    path('delete/<int:pk>/',views.DeleteDetails.as_view(),name='delete'),
]

CRUDbasic/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crud/',include('CRUD.urls')),
]

CRUD/models.py
from django.db import models
from datetime import datetime
# Create your models here.
class RandObject(models.Model):
    objectname=models.CharField(max_length=140,blank=False)
    date_added=models.DateTimeField(default=datetime.now)
    price=models.IntegerField(default=0,blank=False)
    def __str__(self):
        return self.objectname

CRUD/forms.py
from django.utils.translation import gettext_lazy as _  #important!!

from django import forms
from .models import RandObject


class Prod(forms.ModelForm):
    class Meta:
        model=RandObject
        fields=['objectname','price']
        labels={
            'objectname': _('Name'),
        }
    # name=forms.CharField(label='Product Name', max_length=100,required=True )
    # price=forms.IntegerField(label='Price',required=True)

CRUD/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse,reverse_lazy
from django.views import generic
from datetime import datetime

from .models import RandObject
from .forms import Prod

# Create your views here.
class DisplayList(generic.ListView):
    template_name='CRUD/display.html'
    context_object_name='displist'
    def get_queryset(self):
        return RandObject.objects.all()

class DetailView(generic.DetailView):
    model=RandObject
    template_name='CRUD/details.html'

# def enterDetails(request):
#     #if request is POST we process this as form submitted data
#     if request.method=='POST':
#         # create a form instance and populate it with data from the request:
#         fvar=Prod(request.POST)
#         #check if form data valid
#         if fvar.is_valid():
#             #process data from fvar.cleaned_data
#             obj=RandObject() #remember the parentheses here. Paranthesis= an instance. while no parenthesis is the actual function
#             obj.objectname=fvar.cleaned_data["name"]
#             obj.price=fvar.cleaned_data["price"]
#             obj.save()
#             return HttpResponseRedirect(reverse('CRUD:disp'),)
#         else:
#             #if any fields are unfilled
#             return render(request,'CRUD/enter.html',{'form':fvar.as_p(),'error':"All fields are mandatory"})
#     else:
#         fvar=Prod()
#     return render(request,'CRUD/enter.html',{'form':fvar.as_p()})

class EnterDetails(generic.CreateView):     #generic CreateView is used to display a form based off of the model and accept inputs to the db
    form_class=Prod                             #dont need to assign model as the form class accepts a ModelForm which is already built upon a model
    template_name='CRUD/enter.html'
    success_url=reverse_lazy('CRUD:disp') #reverse_lazy() instead of reverse() as the URLconf isnt loaded yet or something

# def editDetails(request,id):
#     r=get_object_or_404(RandObject,pk=id)
#     if request.method=='POST':
#         f=Prod(request.POST,initial={'name':r.objectname,'price':r.price})
#         if f.is_valid():
#             r.objectname=f.cleaned_data["name"]
#             r.price=f.cleaned_data["price"]
#             r.date_added=datetime.now()
#             r.save()
#             return HttpResponseRedirect(reverse('CRUD:disp'),)
#         else:
#             return render(request,'CRUD/edit.html',{'form':f.as_p(),'error':"All fields are mandatory"})
#     else:
#         f=Prod(initial={'name':r.objectname,'price':r.price})
#     return render(request,'CRUD/edit.html',{'form':f.as_p(),'id':id})

class EditDetails(generic.UpdateView):
    model=RandObject    #but for some reason the model needed to be included as well here else it wasnt working
    form_class=Prod
    template_name='CRUD/enter.html'
    success_url=reverse_lazy('CRUD:disp')



# def deleteDetails(request,id):
#     r=get_object_or_404(RandObject,pk=id)
#     r.delete()
#     return HttpResponseRedirect(reverse('CRUD:disp'),)

class DeleteDetails(generic.DeleteView):
    model=RandObject
    success_url=reverse_lazy('CRUD:disp')   #The DeleteView page displayed to a GET request uses a template_name_suffix of '_confirm_delete'.
    # For example, changing this attribute to '_check_delete' for a view deleting objects for the example Author model would cause the default template_name to be 'myapp/author_check_delete.html'.

CRUD/templates/CRUD/details.html
<h1>Object Details</h1>
<ul>
  <li>Item No. {{randobject.id}}
  <li>Name: {{randobject.objectname}}</li>
  <li>Cost: {{randobject.price}}</li>
  <li>Last Updated: {{randobject.date_added}}</li>
  <!-- <li><button>Edit</button></li> -->
  <!-- <li><button>DELETE</button></li> -->
</ul>
<a href="{% url 'CRUD:edit' randobject.id  %}"><button>Update</button></a> <a href="{% url 'CRUD:disp' %}"><button>Back</button></a>

CRUD/templates/CRUD/display.html
<h2>THE CRUD LIST</h2>
<table border=2>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Actions</th>
  </tr>
  {% for list in displist %}
  <tr>
    <td><a href="{% url 'CRUD:details' list.id %}">{{list.objectname}}</a></td>
    <td>{{list.price}}</td>
    <td><a href="{% url 'CRUD:edit' list.id  %}"><button>Update</button></a>
      <a href="{% url 'CRUD:delete' list.id  %}"><button>Delete</button></a></td>
  </tr>
  {% endfor %}
</table><br>
<a href="{% url 'CRUD:enter' %}"><button>Enter Data</button></a>

CRUD/templates/CRUD/edit.html
<!-- {% if error %}
  <strong>{{error}}</strong>
{% endif %} -->
<h1>Edit Data</h1>
  <!-- <form action="{% url 'CRUD:edit' id %}" method='POST'> -->
  <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type=submit value='Save'>
  </form>
 <a href="{% url 'CRUD:disp' %}"><button>Cancel</button></a>

CRUD/templates/CRUD/enter.html
<!-- {% if error %}
  <strong>{{error}}</strong>
{% endif %} -->
<h1>Enter Data</h1>
  <!-- <form action="{% url 'CRUD:enter' %}" method='POST'> -->
  <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type=submit>
  </form>
 <a href="{% url 'CRUD:disp' %}"><button>Cancel</button></a>

CRUD/templates/CRUD/randobject_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>